% Welcome Message
disp("                                                                    ..;===+.")
disp("                                                                .:=iiiiii=+=")
disp("                     Welcome to the Astrodynamics Library!   .=i))=;::+)i=+,")
disp("                                                          ,=i);)I)))I):=i=; ")
disp("                                                       .=i==))))ii)))I:i++  ")
disp("                                                     +)+))iiiiiiii))I=i+:'  ")
disp("                                .,:;;++++++;:,.       )iii+:::;iii))+i='    ")
disp("                             .:;++=iiiiiiiiii=++;.    =::,,,:::=i));=+'     ")
disp("                           ,;+==ii)))))))))))ii==+;,      ,,,:=i))+=:       ")
disp("                         ,;+=ii))))))IIIIII))))ii===;.    ,,:=i)=i+         ")
disp("                        ;+=ii)))IIIIITIIIIII))))iiii=+,   ,:=));=,          ")
disp("                      ,+=i))IIIIIITTTTTITIIIIII)))I)i=+,,:+i)=i+            ")
disp("                     ,+i))IIIIIITTTTTTTTTTTTI))IIII))i=::i))i='             ")
disp("                    ,=i))IIIIITLLTTTTTTTTTTIITTTTIII)+;+i)+i`               ")
disp("                    =i))IIITTLTLTTTTTTTTTIITTLLTTTII+:i)ii:'                ")
disp("                   +i))IITTTLLLTTTTTTTTTTTTLLLTTTT+:i)))=,                  ")
disp("                   =))ITTTTTTTTTTTLTTTTTTLLLLLLTi:=)IIiii;                  ")
disp("                  .i)IIITTTTTTTTLTTTITLLLLLLLT);=)I)))))i;                  ")
disp("                  :))IIITTTTTLTTTTTTLLHLLLLL);=)II)IIIIi=:                  ")
disp("                  :i)IIITTTTTTTTTLLLHLLHLL)+=)II)ITTTI)i=                   ")
disp("                  .i)IIITTTTITTLLLHHLLLL);=)II)ITTTTII)i+                   ")
disp("                  =i)IIIIIITTLLLLLLHLL=:i)II)TTTTTTIII)i'                   ")
disp("                +i)i)))IITTLLLLLLLLT=:i)II)TTTTLTTIII)i;                    ")
disp("              +ii)i:)IITTLLTLLLLT=;+i)I)ITTTTLTTTII))i;                     ")
disp("             =;)i=:,=)ITTTTLTTI=:i))I)TTTLLLTTTTTII)i;                      ")
disp("           +i)ii::,  +)IIITI+:+i)I))TTTTLLTTTTTII))=,                       ")
disp("         :=;)i=:,,    ,i++::i))I)ITTTTTTTTTTIIII)=+'                        ")
disp("       .+ii)i=::,,   ,,::=i)))iIITTTTTTTTIIIII)=+                           ")
disp("      ,==)ii=;:,,,,:::=ii)i)iIIIITIIITIIII))i+:'                            ")
disp("     +=:))i==;:::;=iii)+)=  `:i)))IIIII)ii+'                                ")
disp("   .+=:))iiiiiiii)))+ii;                                                    ")
disp("  .+=;))iiiiii)));ii+                                                       ")
disp(" .+=i:)))))))=+ii+                                                          ")
disp(".;==i+::::=)i=;                                                             ")
disp(",+==iiiiii+,                                                                ")
disp("`+=+++;`                                                                    ")